name: Building recovery

on: workflow_dispatch
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
#  watch:
#   types: [started]

env:
  MANIFEST: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git
  MANIFEST_BRANCH: twrp-12.1
  DEVICE: veux
  DT_LINK: https://github.com/anant-goel/orangefox_device_xiaomi_veux -b OF_12
  DT_PATH: device/xiaomi/veux
  TARGET: recoveryimage
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
         

       - name: Initializing environment
         run: |
            sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
            docker rmi `docker images -q`
            sudo apt-get remove account-plugin-facebook account-plugin-flickr account-plugin-jabber account-plugin-salut account-plugin-twitter account-plugin-windows-live account-plugin-yahoo aisleriot brltty duplicity empathy empathy-common example-content gnome-accessibility-themes gnome-contacts gnome-mahjongg gnome-mines gnome-orca gnome-screensaver gnome-sudoku gnome-video-effects gnomine landscape-common libreoffice-avmedia-backend-gstreamer libreoffice-base-core libreoffice-calc libreoffice-common libreoffice-core libreoffice-draw libreoffice-gnome libreoffice-gtk libreoffice-impress libreoffice-math libreoffice-ogltrans libreoffice-pdfimport libreoffice-style-galaxy libreoffice-style-human libreoffice-writer libsane libsane-common mcp-account-manager-uoa python3-uno rhythmbox rhythmbox-plugins rhythmbox-plugin-zeitgeist sane-utils shotwell shotwell-common telepathy-gabble telepathy-haze telepathy-idle telepathy-indicator telepathy-logger telepathy-mission-control-5 telepathy-salut totem totem-common totem-plugins printer-driver-brlaser printer-driver-foo2zjs printer-driver-foo2zjs-common printer-driver-m2300w printer-driver-ptouch printer-driver-splix
            git config --global user.name "ElytrA8"
            git config --global user.email "manofuranium@gmail.com"         
            sudo -E apt-get clean
            sudo -E apt-get -qq update
            git clone https://github.com/akhilnarang/scripts --depth=1
            cd scripts
            sudo bash setup/android_build_env.sh
            cd .. 
            sudo -E apt-get -qq install bc build-essential zip ccache curl libstdc++6 git wget python gcc clang libssl-dev rsync flex curl  bison aria2
            sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
            sudo chmod a+rx /usr/local/bin/repo
            
       - name: Sync recovery source and device tree
         run: |
             mkdir work
             cd work
             repo init -u $MANIFEST -b $MANIFEST_BRANCH --depth=1 --groups=all,-notdefault,-device,-darwin,-x86,-mips
             repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
             git clone $DT_LINK --depth=1 --single-branch $DT_PATH
             git clone https://github.com/anant-goel/kernel_xiaomi_veux-headers --depth=1 -b twelve kernel/xiaomi/sm6375
             git clone https://github.com/anant-goel/vendor_xiaomi_veux --depth=1 -b thirteen vendor/xiaomi/veux
             git clone https://github.com/LineageOS/android_hardware_xiaomi --depth=1 -b lineage-20 hardware/xiaomi
             
       - name: Build
         run: |
              cd work
              . build/envsetup.sh && lunch twrp_$DEVICE-userdebug && export USE_CCACHE=1 && export ALLOW_MISSING_DEPENDENCIES=true && ccache -M 10G && export CCACHE_DIR=~/ccache/twrp/veux && export CCACHE_EXEC=$(which ccache) && ccache -z && mka $TARGET
             
       - uses: actions/upload-artifact@v2
         with:
          name: recoveryzip
          path: work/out/target/product/*/*.zip

       - uses: actions/upload-artifact@v2
         with:
          name: recoveryimage
          path: work/out/target/product/*/*.img
